### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'common'

### ISSUE THREAD

**Issue by Aaqi123** [MBradbury/iot-trust-task-alloc#24]
Hi, I am trying to run the (iot-trust-task-alloc) on Virtual Machine ( VM WARE) and successfully run the command till step 1- instruction to deploy but when I reached to step 2 and try to run the build command, I get the attached error. 
I will be thankful if you could help me to sort out this error?

![error](https://user-images.githubusercontent.com/114743568/193265938-fd3a90f6-1e4f-4039-bdcc-d6144a75a241.PNG)

**Comment by MBradbury** [comment]
Hello Muhamad,

You need to run the command from the iot-trust-task-alloc directory, as per these docs.

```bash
cd ~/wsn/iot-trust-task-alloc
./tools/setup.py <trust-model> <trust-choose> --deploy ansible
```

You also need to specify the trust model and way in which an edge is chosen. Please note that you need specific hardware for this project to correctly build and deploy.

**Comment by Aaqi123** [comment]
While the simulation process, have you used hardware such as Zolertia and NRF52840? 
Or can we run this GitHub code without this hardware?

**Comment by MBradbury** [comment]
There is no support for simulations. There is only support for deploying on Zolertia RE-Mote Rev.b or nRF 52840.

**Comment by Aaqi123** [comment]
Hi, I cannot find these two devices, from where do you access / purchase these two devices?
